name: CIWIN

on:
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: pdf4qt

      - name: 'VCPKG: Set up VCPKG'
        run: |
          git clone --depth=1 https://github.com/microsoft/vcpkg.git
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg integrate install

      - name: 'VCPKG: Cache vcpkg dependencies'
        uses: actions/cache@v3
        with:
          path: |
            ./vcpkg/downloads
            ./vcpkg/packages
          key: ${{ runner.os }}-vcpkg-v2-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-v2-

      - name: 'VCPKG: Install project dependencies'
        run: |
          .\vcpkg install tbb openssl lcms zlib openjpeg freetype ijg-libjpeg libpng
        working-directory: vcpkg
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.0'
          host: 'windows'
          target: 'desktop'
          dir: '${{ github.workspace }}/qt/'
          install-deps: 'true'
          modules: 'qtspeech qtmultimedia'
          cache: 'true'
          cache-key-prefix: ${{ runner.os }}-qt-660

      - name: Build project
        working-directory: pdf4qt
        run: |
          cmake -B build -S . -DPDF4QT_INSTALL_QT_DEPENDENCIES=ON -DPDF4QT_INSTALL_DEPENDENCIES=ON -DCMAKE_TOOLCHAIN_FILE=$GITHUB_WORKSPACE\vcpkg\scripts\buildsystems\vcpkg.cmake -DPDF4QT_QT_ROOT=$Qt6_DIR -DPDF4QT_INSTALL_MSVC_REDISTRIBUTABLE=ON -DPDF4QT_INSTALL_PREPARE_WIX_INSTALLER=ON -DCMAKE_BUILD_TYPE=Release -DPDF4QT_INSTALL_TO_USR=ON
          cmake --build build -j6
          cmake --install build

      - name: Make Windows ZIP package
        working-directory: pdf4qt/build/usr
        run: |
          7z a -r pdf4qt.zip bin
          
      - name: Upload Windows package
        uses: actions/upload-artifact@v3
        with:
          name: 'pdf4qt-${{ runner.os }}.zip'
          path: .\pdf4qt\build\usr\*.zip
          retention-days: 30
